### ISSUE TITLE
[nvim] [deoplete] Freezes UI on opening .c file

### ISSUE THREAD

**Issue by msva** [Shougo/neco-syntax#2]
Hi there!
I've found, that when I open .c file (even one-liner) with `neco-syntax` enabled, my neovim freezes (ignores any actions like moving cursor, entering commands and so on) for some time (about 5s), and then commits all the actions I made over this time.

Can you advice me how to properly debug the issue and/or get rid of it, please? 😸

**Comment by Shougo** [comment]
I will debug the behavior.
Please upload the minimal vimrc and the reproduce ways from neovim starting and the sample .c file.

**Comment by Shougo** [comment]
I cannot reproduce the behavior.

**Comment by msva** [comment]
the very minimal vimrc (`~/.config/nvim/init.vim` actually) is:

```vim
let &runtimepath.=",/usr/share/vim/vimfiles"
let &runtimepath=substitute(&runtimepath,"/usr/share/nvim/site/after,","\\0/usr/share/vim/vimfiles/after,","")
let g:deoplete#enable_at_startup = 1

packadd! deoplete.nvim
packadd! neco-syntax
```
Removing any of that lines makes it stop freezing.

And this text alone (when saved as init.vim) is enough to produce freeze even on opening empty file named `foo.c`. But let it be
```c
int main() {
}
```
(for test purposes)

P.S. can't reproduce the issue under vim8, tho

**Comment by Shougo** [comment]
I cannot reproduce the behavior.

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set rtp+=~/.cache/dein/repos/github.com/Shougo/neco-syntax/

let g:deoplete#enable_at_startup = 1
```

Why?

**Comment by Shougo** [comment]
```
let &runtimepath.=",/usr/share/vim/vimfiles"
let &runtimepath=substitute(&runtimepath,"/usr/share/nvim/site/after,","\\0/usr/share/vim/vimfiles/after,","")
```

I don't think it is needed.
And please use `set rtp+=` like me.

**Comment by msva** [comment]
Well. I need that magic around runtimepath because there is some system-specific syntax plugins (say, `ebuild` (and other Gentoo's) and `nginx`) installed system-wide in vim site directory (system package manager still doesn't know about nvim), and I need them to be loaded in NeoVim in right order. So I patched nvim's rtpath to include vim's site directory (and after-hooks) 

And except this issue with neco-syntax that voodoo worked fine (until now) :-/

**Comment by Shougo** [comment]
> Well. I need that magic around runtimepath because there is some system-specific syntax plugins (say, ebuild (and other Gentoo's) and nginx) installed system-wide in vim site directory (system package manager still doesn't know about nvim), and I need them to be loaded in NeoVim in right order. So I patched nvim's rtpath to include vim's site directory (and after-hooks)

Please upload `:scriptnames` result and the syntax plugins.

**Comment by Shougo** [comment]
You can check it without deoplete.

`call necosyntax#initialize()`
And please check `s:make_cache_from_syntax()` behavior in `autoload/necosyntax.vim`.

**Comment by msva** [comment]
> `scriptnames` result
```
  1: /etc/vim/sysinit.vim
  2: ~/.config/nvim/init.vim
  3: /usr/share/nvim/runtime/filetype.vim
  4: /usr/share/vim/vimfiles/ftdetect/augeas.vim
  5: /usr/share/vim/vimfiles/ftdetect/cmake.vim
  6: /usr/share/vim/vimfiles/ftdetect/dhcpd.vim
  7: /usr/share/vim/vimfiles/ftdetect/eselect.vim
  8: /usr/share/vim/vimfiles/ftdetect/gentoo.vim
  9: /usr/share/vim/vimfiles/ftdetect/libdns.vim
 10: /usr/share/vim/vimfiles/ftdetect/llvm-lit.vim
 11: /usr/share/vim/vimfiles/ftdetect/llvm.vim
 12: /usr/share/vim/vimfiles/ftdetect/meson.vim
 13: /usr/share/vim/vimfiles/ftdetect/nginx.vim
 14: /usr/share/vim/vimfiles/ftdetect/ninja.vim
 15: /usr/share/vim/vimfiles/ftdetect/ntp.vim
 16: /usr/share/vim/vimfiles/ftdetect/pam.vim
 17: /usr/share/vim/vimfiles/ftdetect/pgn.vim
 18: /usr/share/vim/vimfiles/ftdetect/proto.vim
 19: /usr/share/vim/vimfiles/ftdetect/tablegen.vim
 20: /usr/share/vim/vimfiles/ftdetect/tmux.vim
 21: /usr/share/vim/vimfiles/ftdetect/udev.vim
 22: /usr/share/nvim/runtime/ftplugin.vim
 23: /usr/share/nvim/runtime/indent.vim
 24: /usr/share/nvim/runtime/syntax/syntax.vim
 25: /usr/share/nvim/runtime/syntax/synload.vim
 26: /usr/share/nvim/runtime/syntax/syncolor.vim
 27: ~/.config/nvim/pack/mva/opt/neco-syntax/plugin/necosyntax.vim
 28: ~/.config/nvim/pack/mva/opt/deoplete.nvim/plugin/deoplete.vim
 29: ~/.config/nvim/pack/mva/opt/deoplete.nvim/autoload/deoplete.vim
 30: ~/.config/nvim/pack/mva/opt/deoplete.nvim/autoload/deoplete/init.vim
 31: /usr/share/nvim/runtime/plugin/rplugin.vim
 32: ~/.local/share/nvim/rplugin.vim
 33: /usr/share/nvim/runtime/autoload/remote/host.vim
 34: /usr/share/nvim/runtime/autoload/remote/define.vim
 35: /usr/share/nvim/runtime/autoload/provider/pythonx.vim
 36: /usr/share/nvim/runtime/autoload/provider/python3.vim
 37: /usr/share/nvim/runtime/autoload/provider.vim
 38: ~/.config/nvim/pack/mva/opt/deoplete.nvim/autoload/deoplete/mapping.vim
 39: ~/.config/nvim/pack/mva/opt/deoplete.nvim/autoload/deoplete/util.vim
 40: ~/.config/nvim/pack/mva/opt/deoplete.nvim/autoload/deoplete/handler.vim
 41: /usr/share/nvim/runtime/plugin/gui_shim.vim
 42: /usr/share/nvim/runtime/plugin/gzip.vim
 43: /usr/share/nvim/runtime/plugin/health.vim
 44: /usr/share/nvim/runtime/plugin/man.vim
 45: /usr/share/nvim/runtime/plugin/matchit.vim
 46: /usr/share/nvim/runtime/plugin/matchparen.vim
 47: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 48: /usr/share/nvim/runtime/plugin/rrhelper.vim
 49: /usr/share/nvim/runtime/plugin/shada.vim
 50: /usr/share/nvim/runtime/plugin/spellfile.vim
 51: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 52: /usr/share/nvim/runtime/plugin/tohtml.vim
 53: /usr/share/nvim/runtime/plugin/tutor.vim
 54: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 55: /usr/share/vim/vimfiles/plugin/diffchar.vim
 56: /usr/share/vim/vimfiles/plugin/gentoo-common.vim
 57: /usr/share/vim/vimfiles/plugin/gist.vim
 58: /usr/share/vim/vimfiles/plugin/newebuild.vim
 59: /usr/share/vim/vimfiles/plugin/neweselect.vim
 60: /usr/share/vim/vimfiles/plugin/newinitd.vim
 61: /usr/share/vim/vimfiles/plugin/newmetadata.vim
 62: /usr/share/nvim/runtime/ftplugin/c.vim
 63: /usr/share/nvim/runtime/indent/c.vim
 64: /usr/share/nvim/runtime/syntax/c.vim
 65: /usr/share/vim/vimfiles/after/syntax/c.vim
 66: /usr/share/vim/vimfiles/syntax/atk.vim
 67: /usr/share/vim/vimfiles/syntax/atspi.vim
 68: /usr/share/vim/vimfiles/syntax/cairo.vim
 69: /usr/share/vim/vimfiles/syntax/clutter.vim
 70: /usr/share/vim/vimfiles/syntax/colord.vim
 71: /usr/share/vim/vimfiles/syntax/dbusglib.vim
 72: /usr/share/vim/vimfiles/syntax/evince.vim
 73: /usr/share/vim/vimfiles/syntax/fftw3.vim
 74: /usr/share/vim/vimfiles/syntax/gdkpixbuf.vim
 75: /usr/share/vim/vimfiles/syntax/gimp.vim
 76: /usr/share/vim/vimfiles/syntax/glib.vim
 77: /usr/share/vim/vimfiles/syntax/gnomedesktop.vim
 78: /usr/share/vim/vimfiles/syntax/gobjectintrospection.vim
 79: /usr/share/vim/vimfiles/syntax/gstreamer.vim
 80: /usr/share/vim/vimfiles/syntax/gtk2.vim
 81: /usr/share/vim/vimfiles/syntax/gtk3.vim
 82: /usr/share/vim/vimfiles/syntax/gtkglext.vim
 83: /usr/share/vim/vimfiles/syntax/gtksourceview.vim
 84: /usr/share/vim/vimfiles/syntax/gudev.vim
 85: /usr/share/vim/vimfiles/syntax/gusb.vim
 86: /usr/share/vim/vimfiles/syntax/jsonglib.vim
 87: /usr/share/vim/vimfiles/syntax/libgsf.vim
 88: /usr/share/vim/vimfiles/syntax/libnotify.vim
 89: /usr/share/vim/vimfiles/syntax/librsvg.vim
 90: /usr/share/vim/vimfiles/syntax/libsoup.vim
 91: /usr/share/vim/vimfiles/syntax/libunique.vim
 92: /usr/share/vim/vimfiles/syntax/libwnck.vim
 93: /usr/share/vim/vimfiles/syntax/pango.vim
 94: /usr/share/vim/vimfiles/syntax/poppler.vim
 95: /usr/share/vim/vimfiles/syntax/vte.vim
 96: /usr/share/vim/vimfiles/syntax/xlib.vim
 97: ~/.config/nvim/pack/mva/opt/deoplete.nvim/autoload/deoplete/custom.vim
 98: ~/.config/nvim/pack/mva/opt/neco-syntax/autoload/necosyntax.vim
```
> syntax plugins

All of that listed above?

> check it without deoplete.
> call necosyntax#initialize()

Doesn't freeze

> check `s:make_cache_from_syntax()` behavior in `autoload/necosyntax.vim`.

Can you be a bit more specific, please? What should I do with it?

**Comment by Shougo** [comment]
> All of that listed above?

Too many syntax plugins are loaded.  Why?

You should check your `:syntax list`.

> Can you be a bit more specific, please? What should I do with it?

It scans `:syntax list` result.
You can check the implementation.
`:echo` debug.

> Well. I need that magic around runtimepath because there is some system-specific syntax plugins (say, ebuild (and other Gentoo's) and nginx) installed system-wide in vim site directory (system package manager still doesn't know about nvim), and I need them to be loaded in NeoVim in right order. So I patched nvim's rtpath to include vim's site directory (and after-hooks)

You should not do this.
Because Vim8 runtime files are not compatible with neovim.
I think it is the reason.

**Comment by msva** [comment]
Well, I looked a bit closer at the `:scriptnames` and noticed `/usr/share/vim/vimfiles/after/syntax/c.vim`. All the thing what it do is to load all the syntax plugins mentioned after it:
```
" Vim syntax file

let atk_deprecated_errors = 1
let clutter_deprecated_errors = 1
let evince_deprecated_errors = 1
let gdkpixbuf_deprecated_errors = 1
let gimp_deprecated_errors = 1
let glib_deprecated_errors = 1
let gnomedesktop_deprecated_errors = 1
let gstreamer_deprecated_errors = 1
let gtk2_deprecated_errors = 1
let gtk3_deprecated_errors = 1
let gtksourceview_deprecated_errors = 1
let jsonglib_deprecated_errors = 1
let libgsf_enable_deprecated = 1
let libnotify_enable_deprecated = 1
let librsvg_deprecated_errors = 1
let libsoup_deprecated_errors = 1
let libwnck_deprecated_errors = 1
let pango_deprecated_errors = 1
let poppler_deprecated_errors = 1
let vte_deprecated_errors = 1

runtime! syntax/atk.vim
runtime! syntax/atspi.vim
runtime! syntax/cairo.vim
runtime! syntax/clutter.vim
runtime! syntax/colord.vim
runtime! syntax/dbusglib.vim
runtime! syntax/evince.vim
runtime! syntax/fftw3.vim
runtime! syntax/gdkpixbuf.vim
runtime! syntax/gimp.vim
runtime! syntax/glib.vim
runtime! syntax/gnomedesktop.vim
runtime! syntax/gobjectintrospection.vim
runtime! syntax/gstreamer.vim
runtime! syntax/gtk2.vim
runtime! syntax/gtk3.vim
runtime! syntax/gtkglext.vim
runtime! syntax/gtksourceview.vim
runtime! syntax/gudev.vim
runtime! syntax/gusb.vim
runtime! syntax/jsonglib.vim
runtime! syntax/libgsf.vim
runtime! syntax/libnotify.vim
runtime! syntax/librsvg.vim
runtime! syntax/libsoup.vim
runtime! syntax/libunique.vim
runtime! syntax/libwnck.vim
runtime! syntax/pango.vim
runtime! syntax/poppler.vim
runtime! syntax/vte.vim
runtime! syntax/xlib.vim
```

And if I move it (so nvim doesn't load it) freezes disappears.

Although, all of them also loaded in vim80 and there is no freezes there :-/

**Comment by Shougo** [comment]
It seems too many syntax items.

> Although, all of them also loaded in vim80 and there is no freezes there :-/

Because in Vim8 deoplete does not work.

**Comment by msva** [comment]
> Because in Vim8 deoplete does not work.

Yes, but there is `neocomplete`, and `neco-syntax` seems to work with `neocomplete` too.

So, it seems, the problem appears only when `neco-syntax` runs with exactly `deoplete` (maybe it's `deoplete` issue then?..).

Btw, talking on "many syntax items": it looks like that. Although,
1) it's strange that `neocomplete` is not affected
2) despite vim really lacks a bit of logic in that after-script (to not spam syntax list, but only load syntax plugins that are really needed), it looks like there is no analogs (that would allow to highlight all the C-related syntax that vim's plugin handles) :'(

**Comment by Shougo** [comment]
Really?
Hm.  But you can debug it.
Please check `s:make_cache_from_syntax()`.
Both neocomplete and deoplete call it.

**Comment by msva** [comment]
by the way, I just found that it's not even vim's `c` plugin there!

It's http://www.vim.org/scripts/script.php?script_id=1000 (just installed system-wide in `syntax` dirs and with `c.vim.example` moved to `after/c.vim`, and uncommented all the stuff (see above)).

so, there is a way to reproduce on clean environment:
```shellsession
mkdir -p ~/.config/nvim/pack/moo/opt
cd ~/.config/nvim/pack/moo/opt

git clone https://github.com/Shougo/neco-syntax
git clone https://github.com/Shougo/deoplete.nvim

wget -qO- 'https://vim.sourceforge.io/scripts/download_script.php?src_id=20534' | tar -xzf-
mkdir -p gtk-vim-syntax/syntax gtk-vim-syntax/after/syntax
mv gtk-vim-syntax/*.vim gtk-vim-syntax/syntax/
sed -e 's/^"run/run/' gtk-vim-syntax/c.vim.example > gtk-vim-syntax/after/syntax/c.vim

cd ~/.config/nvim
echo 'packadd! deoplete.nvim
packadd! neco-syntax
packadd! gtk-vim-syntax' > init.vim
nvim --headless +UpdateRemotePlugins +q
echo 'let g:deoplete#enable_at_startup = 1' >> init.vim

cd ~ 
echo 'int main() {
// comment
// comment
// comment
// comment
}' > a.c
```
Now open `a.c` and try to navigate over the file.

**Comment by msva** [comment]
Well, actually it is enough to just `cp c.vim.example after/syntax/c.vim` (without uncommenting), but in that case it freezes on less amount time.

P.S. Probably, I'm not very good tester to debug it (and compare with neocomplete behaviour) and you'll debug it better, but I'll anyway try to debug a bit later.

**Comment by Shougo** [comment]
I get it.  They are very huge files.

**Comment by Shougo** [comment]
Fixed.
